import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DayOne {

    public int calculateResult(int[] input) {
        return Arrays.stream(input).sum();
    }
}
