import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class DayOne {

    private final List<Integer> frequenciesSoFar;
    private int total;

    DayOne() {
        total = 0;
        frequenciesSoFar = new ArrayList<>();
        frequenciesSoFar.add(0);
    }

    int addFrequencyToTotal(int frequency) {
        total += frequency;
        frequenciesSoFar.add(total);
        return total;
    }

    int getFirstRepeatedFrequency(int[] frequencies) {
        while(true) {
            for (int frequency : frequencies) {
                if (frequenciesSoFar.contains(total + frequency)) {
                    return total + frequency;
                }
                frequenciesSoFar.add(addFrequencyToTotal(frequency));
            }
        }
    }
}
