/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class DayOneTest {
    @Test public void noInputGivesZeroOutput() {
        DayOne dayOne = new DayOne();
        assertThat(dayOne.calculateResult(new int[]{})).isEqualTo(0);
    }

    @Test
    public void oneNumberInput() {
        DayOne dayOne = new DayOne();
        assertThat(dayOne.calculateResult(new int[]{1})).isEqualTo(1);
    }

    @Test
    public void finalResult() {
        DayOne dayOne = new DayOne();
        assertThat(dayOne.calculateResult(Input1.INTS)).isEqualTo(518);
    }
}
