/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class DayOneTest {

    private DayOne dayOne;

    @Before
    public void setUp(){
        dayOne = new DayOne();
    }

    @Test
    public void addOneFrequencyToTotal() {
        assertThat(dayOne.addFrequencyToTotal(1)).isEqualTo(1);
        assertThat(dayOne.addFrequencyToTotal(1)).isEqualTo(2);
    }

    @Test
    public void detectRepeatedFrequencyWithoutRepetition() {
        assertThat(dayOne.getFirstRepeatedFrequency(new int[]{1,1,-1,1})).isEqualTo(1);
    }

    @Test
    public void repeatedFrequencyWithRepetition() {
        assertThat(dayOne.getFirstRepeatedFrequency(Input1.INTS)).isEqualTo(72889);
    }

}
